modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="mojanimation_backport"
version="1.0.0"
displayName="Mojanimation Backport"
logoFile = "logo.png"
authors="TheDarkPeasant"
description='''
A backport of Mojang's keyframe animation system to 1.16.5
'''
[[dependencies.mojanimation_backport]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mojanimation_backport]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
